# Generated by Django 2.0.1 on 2018-01-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(max_length=100)),
                ('table_no', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='PostMedia',
        ),
        migrations.DeleteModel(
            name='ProfileInfo',
        ),
    ]
