# Generated by Django 2.0.1 on 2018-01-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_auto_20180114_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationstatus',
            name='status',
            field=models.CharField(default='Vacancy', max_length=100),
        ),
    ]
